### ISSUE TITLE
Telemetry flag with ActiveMQ broker is not supported

### ISSUE THREAD

**Issue by pedroramirezgft** [amqphub/amqp-10-jms-spring-boot#16]
Hello there,

We use an ActiveMQ broker and we've enabled a header with the telemetry flag on our messages, then we've started to receive an error message whenever a message is received on our consumer: 

`o.a.qpid.jms.provider.amqp.AmqpConsumer  : Error on transform: Expected Symbol type but found encoding: STR8:0xa1` 

Working messages are like: 
�p�AP@BC�s�-�-7430405690296218513/1/0�kamel�	harmonize�w��{message body}

Not working messages are like:
�p�AP@BC�r��traceparent�none�s�,�1147805701298596777/1/0�kamel�	harmonize�w��{message body}

We are wondering if there is a configuration we could use in order to fix this issue.
Environment details:
library version: 3.1.6
ActiveMQ version: 5.17.6

Any support is more than welcome :)
Kind regards

**Comment by tabish121** [comment]
The error message would indicate that the client was unable to decode an AMQP type due to there being some incorrect encoding found.  Without further details I cannot say what exactly went wrong but the error indicates that the type it was attempting to decode should have been an AMQP Symbol type but instead a String type was found.  

Would need more details to look further

**Comment by pedroramirezgft** [comment]
Finally we noticed there were an strange character in the encoding method. Thanks for your support!
